[Fix](mlu-ops): revise shell scripts to force user to choose sub-module to compile.
Cambricon/mlu-ops pull request #179
Opened 2022-09-06 07:09 UTC by DanieeelLiu

Thanks for your contribution and we appreciate it a lot. 

## 1. Motivation

The current build.sh will build bangc-ops and bangpy-ops together, user want to build sub-module seperately.

## 2. Modification
Modified build.sh to support build sub-module separately.
Modified test.sh to support test sub-module separately.
Modified .github/workflow/ci.yaml according to modification of build.sh and test.sh.

2022-09-06 08:01 UTC, zhsj requested changes

2022-09-06 08:01 UTC, zhsj commented on .github/workflows/ci.yaml
> +          bash -c "./test.sh --sub_module=bangc && ./test.sh --sub_module=bangpy --target=mlu270"
现在会同时测试mlu270、290、370，这里只写 --target=mlu270 可以吗？

2022-09-06 08:09 UTC, zhsj requested changes

2022-09-06 08:09 UTC, zhsj commented on .github/workflows/ci.yaml
> +          bash -c "./build.sh --sub_module=bangc && ./build.sh --sub_module=bangpy"
这些分开来写吧？log里也能知道出错的话，是在bangc还是bangpy

- name: build bangc
  run: xxx ./build.sh --sub_module=bangc
- name: build bangpy
  run: xxx ./build.sh --sub_module=bangpy

2022-09-07 01:40 UTC, zhangyicole approved these changes

2022-09-08 03:03 UTC, zhsj approved these changes

2022-09-08 03:43 UTC, WangYuan-cn approved these changes

2022-09-08 03:43 UTC, merged