[Feature](bangc-ops): fix libmluops.so file symbol visibility
Cambricon/mlu-ops pull request #379
Opened 2023-02-01 08:27 UTC by wushaoqiang2168

Thanks for your contribution and we appreciate it a lot. 

## 1. Motivation

Please describe your motivation and the goal you want to achieve through this pull request.

## 2. Modification

Please briefly describe what modification is made in this pull request, and indicate where to make the modification.

## 3. Test Report

If you want to know how to do operator testing, you can see [GTest-User-Guide-zh](../docs/GTest-User-Guide-zh.md).

### 3.1 Modification Details

#### 3.1.1 Accuracy Acceptance Standard

For static threshold standard details, see: [MLU-OPS Accuracy Acceptance Standard](../docs/MLU-OPS-Accuracy-Acceptance-Standard.md).

- [ ] diff1, diff1 <= 3e-3
- [ ] diff2, diff2 <= 3e-3

#### 3.1.2 Operator Scheme checklist

|     No.        |                 Details              |            Check Results             |
|----------------|--------------------------------------|--------------------------------------|
|        1       |Supported hardware                    |             MLU370<br>MLU590         |
|        2       |Job types                             |          block <br> U1 <br> U4       |
|        3       |Layouts                               |          NHWC 、NCHW、ARRAY etc      |
|        4       |Whether multi-dimensions are supported|                                      |
|        5       |Whether element zero is supported     |                                      |
|        6       |Data type(half/float)                 |           half / float etc           |
|        7       |Whether there is size limit           |                                      |

#### 3.1.3 New Feature Test

If you have checked the following items, please tick the relevant box.

- [ ] Data type test
- [ ] Multidimensional tensor test
- [ ] Layout test
- [ ] Different size/integer remainder end segment/alignment misalignment test
- [ ] Zero dimensional tensor test/zero element test
- [ ] stability test
- [ ] Multiple platform test
- [ ] Gen_case module test
- [ ] Nan/INF tests 
- [ ] Bug fix tests
- [ ] For memory leak check details, see[GTest-User-Guide-zh](../docs/GTest-User-Guide-zh.md).
- [ ] For code coverage check details, see: [GTest-User-Guide-zh](../docs/GTest-User-Guide-zh.md).
- [ ] For I/O calculation efficiency check details, see: [MLU-OPS Performance Acceptance Standard](../docs/MLU-OPS-Performance-Acceptance-Standard.md).

#### 3.1.4 Parameter Check

When a new operator is submitted, the test points are given and the test results are stated.

|                   Test Point                    | Acceptance Standard | Test Result (Error Message) |
| ----------------------------------------------- | --------------------| --------------------------- |
| Whether it conforms to the operator restriction |     Normal error    |                             |
| Whether illegal parameters are passed           |     Normal error    |                             |

### 3.2 Accuracy Test

For the cases used in the New Feature Test section, the features and the number of cases are recorded here. When multiple operations are tested, multiple tables are needed to include details of these operations.

Operation:

|Test Point           | Description                      | Quantity |  Comment |
|----------           |----------------------------------|----------|  --------|
|Data type test       |half/float/int8                   |          |          |
|Mult-tensor test     |Supports 1-8 dims                 |          |          |
|Layout test          |Supports NCHW/NHWC                |          |          |
|Zero element test    |Whether to support this test      |          |          |
|Stability test       |--gtest_repeat=NUM<br>--thread=NUM|          |          |
|Mult-platform test   |MLU370/MLU590                     |          |          |
|Nan/INF test         |Whether to support this test      |          |          |

### 3.3 Performance Test

See [MLU-OPS Performance Acceptance Standard](../docs/MLU-OPS-Performance-Acceptance-Standard.md) for details.

Platform：MLU370

|Operation|Mlu_hardware_time(us)|Mlu_interface_time(us)|Mlu_io_efficiency|Mlu_compute_efficiency|Mlu_workwpace_size(Bytes)|Data_type|Shape|
|-------|----|----|-----|----|----|----|-----|
|op_name|    |    |     |    |    |    |     |
|op_name|    |    |     |    |    |    |     |

Platform：MLU590

|Operation|Mlu_hardware_time(us)|Mlu_interface_time(us)|Mlu_io_efficiency|Mlu_compute_efficiency|Mlu_workwpace_size(Bytes)|Data_type|Shape|
|-------|----|----|----|----|----|----|-----|
|op_name|    |    |    |    |    |    |     |
|op_name|    |    |    |    |    |    |     |

### 3.4 Summary Analysis

Please give a brief overview here, if you want to note and summarize the content.

2023-02-01 12:36 UTC, jerryjiahaha requested changes

2023-02-01 12:36 UTC, jerryjiahaha commented on bangc-ops/gen_mluops.py
> +mluop_abi_version = "MLUOP_ABI_1.0 {"
最好做一下兼容性测试，比如一个应用程序，基于上个版本mlu ops链接，运行时替换成当前版本，看一下是否能够使用

2023-02-02 09:35 UTC, wushaoqiang2168 commented on bangc-ops/gen_mluops.py
> +mluop_abi_version = "MLUOP_ABI_1.0 {"
好的，多谢建议

2023-02-02 09:35 UTC, wushaoqiang2168 commented on bangc-ops/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/libmluops.map")
已修改为LINK_FLAG

2023-02-02 09:36 UTC, wushaoqiang2168 commented on bangc-ops/gen_mluops.py
> +                    if(line[i].find('(') != -1):
参考重新实现了一版

2023-02-03 03:27 UTC, wushaoqiang2168 commented
测试报告：https://wiki.cambricon.com/pages/viewpage.action?pageId=240779458

2023-02-03 03:36 UTC, wushaoqiang2168 commented
[[](url)

2023-02-03 03:39 UTC, jerryjiahaha approved these changes

2023-02-06 02:07 UTC, WangYuan-cn commented on bangc-ops/README.md
> +  - 在编译阶段，将根据`libmluops.map`文件中global字段定义的符号表，将动态库`libmluops.so`中除global中定义的符号外，其他符号定义为local。
```suggestion
  - 在编译阶段依据`libmluops.map`文件中global字段定义的符号表，将动态库`libmluops.so`中除global中定义的符号外的其他符号定义为local。
```

2023-02-06 02:10 UTC, WangYuan-cn commented on bangc-ops/README.md
> +- gen_mluops.py 脚本说明
```suggestion
- gen_mluops.py
```

2023-02-06 03:46 UTC, wushaoqiang2168 commented on bangc-ops/README.md
> +  - 在编译阶段，将根据`libmluops.map`文件中global字段定义的符号表，将动态库`libmluops.so`中除global中定义的符号外，其他符号定义为local。
已改

2023-02-06 03:46 UTC, wushaoqiang2168 commented on bangc-ops/README.md
> +- gen_mluops.py 脚本说明
已改

2023-02-06 07:56 UTC, WangYuan-cn approved these changes

2023-02-07 06:35 UTC, duzekunKTH approved these changes

2023-02-07 06:46 UTC, merged