feat(bangpy): add bangpy develop support.
Cambricon/mlu-ops pull request #5
Opened 2021-12-22 08:17 UTC by withfall

1. Add bangpy python api develop support.
2. Collate bangc files.

2021-12-23 03:20 UTC, zhsj commented on .github/workflows/ci.yaml
> +          rm -rf bangpy-ops/outs
这个命令是 `docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/cambricon/cnnl-ci:v0.4-ubuntu1604 rm -rf bangc-ops/build` 和 `rm -rf bangpy-ops/outs` 两部分。这应该不是期望的。

可以在本地测试一下，`run`后面就是bash脚本，和在本地跑 `docker run image command && command2` 是一个效果。想要 `command && command2` 同时在容器里跑，应该这样 `docker run image bash -c "command && command2"`

2021-12-23 03:28 UTC, withfall commented on .github/workflows/ci.yaml
> +          rm -rf bangpy-ops/outs
是的，已经把clean动作移到 test.sh 最后。

2021-12-23 06:23 UTC, withfall commented on .github/workflows/ci.yaml
> +          rm -rf bangpy-ops/outs
把clean动作移到 test.sh 最后，可能 会有test 中fail 中断退出 未 clean的情况。采用bash -c 的方法。

2021-12-23 07:03 UTC, zhsj commented
![image](https://user-images.githubusercontent.com/227180/147201702-36448fe5-7f55-4fdf-b5c0-3f69995f2bba.png)


bangc的测试没有运行？

2021-12-23 07:52 UTC, withfall commented
> ![image](https://user-images.githubusercontent.com/227180/147201702-36448fe5-7f55-4fdf-b5c0-3f69995f2bba.png)
> 
> bangc的测试没有运行？

已经修复。

2021-12-23 07:53 UTC, UniqueSquirrel approved these changes

2021-12-23 07:58 UTC, zhangyicole approved these changes

2021-12-23 08:21 UTC, jasonsi1993 approved these changes

2021-12-23 08:49 UTC, zhsj approved these changes

2021-12-23 09:00 UTC, zhsj reviewed
two minor typos..

2021-12-23 09:00 UTC, zhsj commented on test.sh
> +# You need to run build.sh, befor running this script.
```suggestion
# You need to run build.sh, before running this script.
```

2021-12-23 09:00 UTC, zhsj commented on test.sh
> +# Test BANGPy Operato
```suggestion
# Test BANGPy operator
```

2021-12-23 09:18 UTC, jerryjiahaha requested changes

2021-12-23 09:18 UTC, jerryjiahaha commented on bangpy-ops/README.md
> +详情可以参考文档 [BANGPy-OPS 算子开发流程.md](../docs/BANGPy-OPS算子开发流程.md)。
这个文件不存在，是不是漏上传了

2021-12-23 09:40 UTC, withfall commented on test.sh
> +# You need to run build.sh, befor running this script.
已修改

2021-12-23 09:41 UTC, withfall commented on test.sh
> +# Test BANGPy Operato
已修改

2021-12-23 09:55 UTC, UniqueSquirrel commented on bangpy-ops/README.md
> +2. 在 `mlu-ops/bangpy-ops/ops/` 路径下创建以 `test_` 为前缀的算子测试文件，添加测试代码，可以参考[test_add.py](./ops/add/test_add.py)进行添加。
```suggestion
2. 在算子文件夹下创建以 `test_` 为前缀的算子测试文件，添加测试代码，可以参考[test_add.py](./ops/add/test_add.py)进行添加。
```

2021-12-23 11:37 UTC, Weijie-itsum commented on README.md
> +- Python环境：
如果bangc和bangpy运行都是分开的话，环境准备是不是也可以分开？例如开发bangc的话可以不需要python环境，开发bangpy的话也可以不安装proto/xml之类的

2021-12-23 12:12 UTC, withfall commented on README.md
> +- Python环境：
开发环境采用一套，目前运行测试分开，后面会将两者合为一个，并生成一个lib， 不然没法release。

2021-12-23 12:13 UTC, withfall commented on bangpy-ops/README.md
> +详情可以参考文档 [BANGPy-OPS 算子开发流程.md](../docs/BANGPy-OPS算子开发流程.md)。
已添加

2021-12-24 02:26 UTC, zhangyicole commented on docs/bangpy-docs/BANGPy-OPS算子开发流程.md
> +### 2. API 接口设计
这一块最好改一下，改成符合python语言规范？

2021-12-24 02:57 UTC, UniqueSquirrel commented on docs/bangpy-docs/BANGPy-OPS算子开发流程.md
> +注意： API 接口设计为 C 风格接口，不允许出现 C++ 的语法风格。
```suggestion
```

2021-12-24 03:11 UTC, merged